--Ders Tablosu
SELECT * FROM PLSQL_DERS WHERE DERSID=1;
PLSQL_OGRENCIDERS
SELECT * FROM PLSQL_OGRENCI for update;
SELECT * FROM PLSQL_OGRENCIDERS

--Öðrenci Tablosu
SELECT * FROM PLSQL_STAJ.PLSQL_Ogrenci; --FOR UPDATE;

SELECT * FROM PLSQL_OGRENCIDERS

PLSQL_INS_OTOMASYON_OGRENCI_SP 
