CREATE OR REPLACE PROCEDURE PLSQL_SEL_OGRENCIALL_SP(RC1 OUT SYS_REFCURSOR) AS
BEGIN

   OPEN RC1 FOR
      SELECT O.OGRENCINO     "ÖGRENCÝNUMARASI",
             O.OGRENCIADI    "ÖÐRENCÝ ADI",
             O.OGRENCISOYADI "ÖÐRENCÝ SOYADI"
      
        FROM PLSQL_OGRENCI O
       WHERE O.STATUSIND = 1;

END PLSQL_SEL_OGRENCIALL_SP;
/
