CREATE OR REPLACE PROCEDURE PLSQL_SEL_DERSALL_SP(RC1 OUT SYS_REFCURSOR) AS
BEGIN
   OPEN RC1 FOR
      SELECT D.DERSID     "DERSID",
             D.DERSKODU   "DERSKODU",
             D.DERSADI    "DERSADI",
             D.DERSKREDI  "DERSKREDI",
             D.DERSDONEMI "DERSDONEMI"
      
        FROM PLSQL_DERS D
       WHERE D.STATUSIND = 1;

END PLSQL_SEL_DERSALL_SP;
/
