CREATE OR REPLACE PROCEDURE PLSQL_SEL_OGRENCI_SP
(
   p_OGRENCINO IN plsql_ogrenci.ogrencino%TYPE,
   RC1         OUT SYS_REFCURSOR
) AS
BEGIN

   OPEN RC1 FOR
      SELECT O.OGRENCINO,
             O.OGRENCIADI,
             O.OGRENCISOYADI
        FROM PLSQL_OGRENCI O
       WHERE O.OGRENCINO = p_OGRENCINO
         AND O.STATUSIND = 1;

END PLSQL_SEL_OGRENCI_SP;
/
